version: '3.5'
services:
  db:
    container_name: db
    image: mongo:latest
    networks:
      - serv
    volumes:
      - mongo:/data/db
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --quiet | grep 1      
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 10s

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./dockerfile
    depends_on:
      db:
        condition: service_healthy
    networks:
      - serv
    ports:
      - "3000:3000"


networks:
  serv:
volumes:
  mongo:
